"""create hunts table

Revision ID: 66bbb0841ff5
Revises: 
Create Date: 2026-04-03 23:13:49.025124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bbb0841ff5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunts_id'), 'hunts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hunts_id'), table_name='hunts')
    op.drop_table('hunts')
    # ### end Alembic commands ###
